### PR TITLE
Simplify the project. Update colors to match Figma @ v0.2

### PR DESCRIPTION
**Pull request by MikeRawding**
This greatly simplifies the project.  The only real outputs are a `colors.js` and `colors.less` file.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1201488620132333

### CODE REVIEW

**Review by spencerkingman-niche — APPROVED** [review]
Love it. When we use this in website, which will have a lot of colors not in this palette, do you think we should just use this where possible and maintain a separate website-only list of colors as a file in that repo?

**Comment by spencerkingman-niche** [comment]
If you think this is totally ready, I would like to do a PR that starts using this in Website.

**Comment by MikeRawding** [comment]
@spencerkingman-niche
If you want to make a PR for website that would be awesome!  Test it referencing `1.2.0-beta5` and see if everything works the way you expect.  If it does, we'll merge this in to master and publish it as ~~`1.2.0`~~ `1.0.0`.

Yes, I think Website will need to maintain its own file with the old colors (which are hopefully not used in any new designs).  In Pando we old colors in a file called `legacyColors.js`.  This makes it really obvious if you're using old colors because you see the file name when you import it into your JSS.

I don't think it will be as obvious in Website.  We certainly should rename the current `_colors.less` to `_legacyColors.less`.  Then `_variable.less` would have
```less
@import '_legacyColors';
@import '~@nicheinc/expedite-tokens/dist/colors/colors.less';
```

That much is pretty clear.  The problem comes when you go to use them in some other `.less` file.  You just use the color name, so whether or not it's coming from the legacy set is not obvious.  However, the naming convention of the new colors is different and maybe that's enough.

We also need to remove collisions from the existing `_colors.less` in website.  I just took a peak and see this block of collisions.

```less
@warm100: #fbf5f2;
@warm200: #f3e9e3;
@jade300: #09ee97; // different in new colors!
@jade400: #00df8b;
@jade500: #00be76;
@green400: #66BDA3;
@green800: #004436;
@green900: #003024;
@red600: #b20a00;
@gray600: #565656;
@gray900: #1b1b1b;
@blue600: #295AA2;
```

This block should also be removed and references updated to remove the `-` from the color name (e.g. `@green-100` is now available as `@green100`)

```less
@green-100: #f4faf8;
@green-200: #e3efec; // different in new colors
@green-500: #009266;
@green-700: #016853;
...
@red-500: #E63227;
```

It looks like the value of two colors have actually changed, so we will need to get a sign off from design as well.

**Comment by MikeRawding** [comment]
@spencerkingman-niche have you started tinkering with this in Website yet?  Looks like it should work and I'm think I'm just going to merge and publish this as ~~`1.2.0`~~ `1.0.0`.

**Review by khadgis — APPROVED** [review]
Looks good! Colors match :+1:

**Pull request merged**
